### ISSUE TITLE
[Bug] after update to 4.4.0 TypeError: callbacks[i] is not a function

### ISSUE THREAD

**Issue by jmesa-sistel** [webpack-contrib/copy-webpack-plugin#217]
Compiling an angular app generated with angular cli
I have updated to 4.4.0 and I get the next error:
```
C:\Proyectos\BPS\src\webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40
                callbacks[i](err, result);
                            ^

TypeError: callbacks[i] is not a function
    at Storage.finished (C:\Proyectos\BPS\src\webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40:15)
    at C:\Proyectos\BPS\src\webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:77:9
    at C:\Proyectos\BPS\src\webapp\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:167:5)
```

**Comment by skorunka** [comment]
As a reference see SO: https://stackoverflow.com/questions/48684276/angular-cli-gives-me-typeerror-callbacksi-is-not-a-function-when-i-ng-serv/48684727

**Comment by evilebottnawi** [comment]
@jmesa-sistel somebody can create minimum reproducible test repo. Seems regression. Need fix asap, but i can't reproduce.

**Comment by jmesa-sistel** [comment]
@evilebottnawi 
Just create an angular app using last angular cli (1.6.8)
Check [https://github.com/angular/angular-cli/issues/9550](https://github.com/angular/angular-cli/issues/9550)

**Comment by evilebottnawi** [comment]
Investigate

**Comment by dddent** [comment]
It's reproducible by creating and starting a new app using angular cli
`ng new testapp && cd testapp && ng serve`

**Comment by rahuly1390** [comment]
It is solved by installing the plugin
npm install copy-webpack-plugin@4.3.1

**Comment by minan61** [comment]
NOT solved with npm install copy-webpack-plugin@4.3.1 here

**Comment by gajdot** [comment]
@minan61 If you use jenkins or docker you need to install it after cli, then it should work.

**Comment by rahuly1390** [comment]
If it's not working downgrade to 
`npm install copy-webpack-plugin@4.3.0`

**Comment by evilebottnawi** [comment]
https://github.com/angular/angular-cli/issues/9550#issuecomment-364107884

**Comment by evilebottnawi** [comment]
Veru strange. Pify does not callback here https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/writeFile.js#L12
